theme = "everforest_dark"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
true-color =true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false



